# Generated by Django 4.1.5 on 2023-01-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', models.ImageField(upload_to='img/', verbose_name='Графики')),
                ('tables', models.TextField(verbose_name='Таблицы')),
            ],
            options={
                'verbose_name': 'Статистика востребованности',
                'verbose_name_plural': 'Статистики востребованности',
            },
        ),
    ]
