# Generated by Django 4.1.5 on 2023-01-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_geographystatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_1', models.ImageField(upload_to='img/', verbose_name='График')),
                ('graph_2', models.ImageField(upload_to='img/', verbose_name='График')),
                ('graph_3', models.ImageField(upload_to='img/', verbose_name='График')),
                ('graph_4', models.ImageField(upload_to='img/', verbose_name='График')),
                ('graph_5', models.ImageField(upload_to='img/', verbose_name='График')),
                ('graph_6', models.ImageField(upload_to='img/', verbose_name='График')),
                ('graph_7', models.ImageField(upload_to='img/', verbose_name='График')),
            ],
            options={
                'verbose_name': 'Статистика навыков',
                'verbose_name_plural': 'Статистики навыков',
            },
        ),
    ]
